### ISSUE TITLE
attune.load fails if provided a time argument

### ISSUE THREAD

**Issue by jscheeler1** [wright-group/attune#162] opened 2022-08-22 14:18 UTC
Reproduce by :

```
import attune

opa = "w2"
instr = attune.load(opa, time = '2022-08-19T19:45:47.205570-05:00')
attune.store(instr)
```
also fails for time = '5 minutes ago'.  Works if no time argument is provided.

@ksunden says this is caused by Issue #157

**Comment by ksunden** [comment] 2022-08-22 14:19
Closing as duplicate of #157

**Closed** 2022-08-22 14:20 UTC
Labels: bug
