### ISSUE TITLE
ensure colormaps plotted in colorbar are correct given signed attr of channel

### ISSUE THREAD

**Issue by darienmorrow** [wright-group/attune#54] opened 2019-05-06 23:19 UTC

**Comment by untzag** [comment] 2019-06-02 20:35
@darienmorrow from private conversations, I think that this is your argument:
 
- WrightTools artists automatically derive colormaps from the channel sign attribute, which is itself derived from shots processing
- sometimes attune will be given data that was processed with "incorrect" shots processing tools, such that channels are marked as signed even though they are best understood as single-sign
- therefore attune should enforce colorbar preferences on a workup-function level, and ignore channel signed attributes

could you confirm

**Comment by darienmorrow** [comment] 2019-06-02 20:59
Gosh, my memory if this issue was that the heatmap (working definition of heatmap is the thing subplot representing your 2D data) and the colorbar were differing in which colormap they were using. For instance, https://github.com/wright-group/attune/blob/56a85f9664d75213858ecec9ce57ff70797a9662/attune/workup/_plot.py#L22
will make a heatmap whose colormap is determined by the `signed` kwarg of the data object passed. However,  https://github.com/wright-group/attune/blob/56a85f9664d75213858ecec9ce57ff70797a9662/attune/workup/_plot.py#L43 will always plot the `default` colormap inside the colorbar. 

I think the original purpose of the issue was to say that we should go back through our plotting routines and make sure that both the colorbar and the heatmap were using the same colormap.

**Comment by darienmorrow** [comment] 2019-06-02 21:01
My inclination is to have the plotting methods respect the `signed` kwarg. I don't hold strongly to this inclination, though. An easy compormise is to offer a user-facing kwarg which allows them to specify signed vs not...

**Comment by ksunden** [comment] 2020-12-10 19:13
I believe this issue was actually caused by a bug in PyCMDS data file writing itself (which incorrectly recorded the `signed` attribute of disabled channels). Thus for now I think I will close this, though there may still be related issues lurking.

That said, I would tend to believe that e.g. `tune_test` or `intensity` should _always_ be plotting in the `default` colormap, rather than the `signed` colormap as these are workup methods that are inherently mono-polar)

**Closed by ksunden** 2020-12-10 19:13 UTC
Labels: bug, enhancement
